# Generated by Django 5.2.6 on 2025-09-13 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(choices=[('40', '40'), ('41', '41'), ('42', '42')], default='40')),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('sepatu', 'Sepatu'), ('bola', 'Bola'), ('jersey', 'Jersey'), ('slingbag', 'Slingbag'), ('celana', 'Celana')], default='bola')),
                ('total_sold', models.PositiveIntegerField(default=0, editable=False)),
                ('is_featured', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
