# Generated by Django 5.2.6 on 2025-09-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_total_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('anak-anak', 'Anak-anak'), ('dewasa', 'Dewasa')], default='dewasa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
