# Generated by Django 5.2.6 on 2025-09-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_category_alter_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_sold',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
