# Generated by Django 5.2.6 on 2025-09-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_total_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sepatu', 'Sepatu'), ('bola', 'Bola'), ('jersey', 'Jersey'), ('slingbag', 'Slingbag')], default='dewasa'),
        ),
    ]
